### ISSUE TITLE
Make a 0.7.0 release

### ISSUE THREAD

**Issue by psivesely** [SpinResearch/lamport.rs#16]
Before `merkle_sigs.rs` can be update to ring 0.13.0 in order to eventually fix https://github.com/SpinResearch/RustySecrets/issues/71, the changes in https://github.com/SpinResearch/lamport_sigs.rs/pull/15 need to be shipped in a new release. After that https://github.com/SpinResearch/merkle_sigs.rs/pull/7 can be merged, and then finally we take care of https://github.com/SpinResearch/RustySecrets/pull/74 (and then https://github.com/SpinResearch/RustySecrets/issues/73).

**Comment by romac** [comment]
If I didn't make a mistake, version 0.6.0 has been published on the 10th of August: https://crates.io/crates/lamport_sigs

**Comment by psivesely** [comment]
My bad. Updated.

**Comment by romac** [comment]
Sorry, I meant that version 0.6.0 is already published and already integrates those changes, does it not?

**Comment by psivesely** [comment]
Yeah, I guess I missed that? Closing.
